name: EKS dev-Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'select the environment to deploy'
        required: true
        type: choice
        options:
        - dev
        - sandbox
        - prod 
permissions: 
  id-token: write  
  contents: read 

jobs:
  terraform:
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials for dev
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.TERRAFORM_DEPLOY_DEV_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: setup node.js for terraform 
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd Terraform/dev
          terraform init -reconfigure -backend-config="bucket=${{ secrets.TERRAFORM_DEV_BACKEND_BUCKET }}" -backend-config="region=${{ vars.AWS_REGION }}"

      - name: Terraform Plan
        run: |
          cd Terraform/dev
          terraform plan -out=tfplan
          
      - name: Terraform Apply
        run: |
          cd Terraform/dev
          terraform apply tfplan
